spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000 # max time to connect to smtp server
          timeout: 5000  # max time to wait response from server
          writetimeout: 5000  # max time to send mail context to server
