spring:
  jpa:
    show-sql: false
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      properties:
        spring.json.add.type.headers: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: http://product-service:8080
          user-service:
            url: http://user-service:8081
    