spring:
  jpa:
    show-sql: false
  #  data:
  #    redis:
  #      host: redis
  #      port: 6379

  elasticsearch:
    uris: http://elasticsearch:9200
    repositories:
      enabled: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.lendmate.productservice.event.StockDecreaseEvent

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}